RavadGarWebSite/Models/News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavadGarWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.NewsImages = new HashSet<NewsImage>();
        }
    
        public int NewsCode { get; set; }
        public string NewsTitle { get; set; }
        public string Summary { get; set; }
        public string NewsContent { get; set; }
        public string Image { get; set; }
        public string Category { get; set; }
        public Nullable<int> Visit { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsImage> NewsImages { get; set; }
    }
}

RavadGarWebSite/Models/ViewModels/NewsViewModel.cs
using RavadGarWebSite.Framwork.BaseClasses.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RavadGarWebSite.Models.ViewModels
{
    public class NewsViewModel
    {
        public long NewsCode { get; set; }
        public string NewsTitle { get; set; }
        public string Summary { get; set; }
        public string NewsContent { get; set; }
        public string Image { get; set; }
        public string Category { get; set; }
        public int Visit { get; set; }
        public string InsertDateTime { get; set; }

        public static NewsViewModel ConvertNewsToNewsViewModel(News n)
        {
            var newsVM = new NewsViewModel();
            newsVM.Category = n.Category;
            newsVM.Image = n.Image;
            newsVM.InsertDateTime = DateTimeUtility.ConvertDatetimeToStringShmasi(n.InsertDateTime);
            newsVM.NewsCode = n.NewsCode;
            newsVM.NewsContent = n.NewsContent;
            newsVM.NewsTitle = n.NewsTitle;
            newsVM.Summary = n.Summary;
            newsVM.Visit = (int)n.Visit;
            return newsVM;
        }
    }
}

RavadGarWebSite/Controllers/NewsController.cs
using Newtonsoft.Json;
using RavadGarWebSite.Framwork.BaseClasses.Utilities;
using RavadGarWebSite.Models;
using RavadGarWebSite.Models.DAL;
using RavadGarWebSite.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace RavadGarWebSite.Controllers
{
    [HandleError(ExceptionType = typeof(Exception), View = "~/Error/Index")]
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index(int id)
        {
            var news = NewsUtility.GetNews(id);
            return View(news);
        }
        public ActionResult All()
        {
            var news = NewsUtility.getAllNews();
            return View(news);
        }
        public ActionResult GetLastNews(int top)
        {
            var res = NewsUtility.getTopNews(top);
            List<NewsViewModel> resVM = new List<NewsViewModel>();
            foreach (var n in res)
            {
                resVM.Add(NewsViewModel.ConvertNewsToNewsViewModel(n));
            }
            return View(resVM);
        }
        public ActionResult GetLastNewsCol(int top)
        {
            var res = NewsUtility.getTopNews(top);
            return PartialView(res);
        }
        public ActionResult GetNews(int id = 1)
        {
            var news = NewsUtility.GetNews(id);
            if (news == null)
                return View(new NewsViewModel() { NewsTitle = "خبر مورد نظر موجو نیست." });
            var newsModel = NewsViewModel.ConvertNewsToNewsViewModel(news);

            return View(newsModel);
        }

        public ActionResult List(int id = 1)
        {
            List<News> res = new List<News>();
            int count = 10;
            int low = (id - 1) * count;
            int high = id * count;
            try
            {
                res = NewsUtility.getNewsIn(low, high);
            }
            catch (Exception)
            {

            }

            ViewBag.NewsCount = (int)NewsUtility.GetNewsCount();
            ViewBag.PageNewsCount = count;
            return View(res);
        }


    }
}

RavadGarWebSite/Views/News/All.cshtml
@model List<RavadGarWebSite.Models.News>
@{
    ViewBag.Title = "All";
    Layout = "~/Views/shared/_homeLayout.cshtml";
}
<div class="container" id="productView">
    <div class="row">
        <div class="col-md-8">
            <div class="blockRow">

                @foreach (var item in Model)
            {
                    <a href="#" class="smallArticleImage">
                        <img src="~/uploadedimages/news/ThumbNail/@item.Image">
                    </a>
                    <a href="/news/@item.NewsCode" class="articleTitle">@item.NewsTitle</a>
                    <br>
                    <span class="date">@item.InsertDateTime.Day - @item.InsertDateTime.Month - @item.InsertDateTime.Year</span>
                    <div class="clearb"></div>
                }
            </div>
        </div>
        <div class="col-md-4">
            <div class="rollProductsMainDiv block" id="peoplarPrds">
                <div class="right-blocks-title">
                    <h2>آخرین مقالات</h2>
                    <a class="showalllink" href="#" title="محصولات جدید">مشاهده همه</a>
                    <div class="clearb"></div>

                </div>
                <div class="paneBody">
                    @Html.Action("GetLastArticlesCol", "Article", new { top = 5 })
                </div>
            </div>
        </div>
    </div>
</div>

RavadGarWebSite/Views/News/GetLastNews.cshtml
@model List<RavadGarWebSite.Models.ViewModels.NewsViewModel>

RavadGarWebSite/Views/News/GetLastNewsCol.cshtml
@model IEnumerable<RavadGarWebSite.Models.News>



<ul>
    @foreach (var item in Model)
    {
        <li>
            <a href="#" class="smallArticleImage">
                <img src="~/uploadedimages/news/ThumbNail/@item.Image">
            </a>
            <a href="/news/@item.NewsCode" class="articleTitle">@item.NewsTitle</a>
            <br>
            <span class="date">@item.InsertDateTime.Day - @item.InsertDateTime.Month - @item.InsertDateTime.Year</span>
            <div class="clearb"></div>
        </li>

    }
</ul>

RavadGarWebSite/Views/News/Index.cshtml
@model RavadGarWebSite.Models.News

@{
    Layout = "~/Views/shared/_homeLayout.cshtml";
}

<div class="container" id="productView">
    <div class="col-md-8">
        <div class="blockRow">
            <div class="row">
                <div class="col-md-12 texts">
                    <h1 id="titr">@Model.NewsTitle</h1>
                    <div class="smallInfo">
                        <span class="priceTitr">تاریخ درج خبر:</span>
                        <span class="priceValue price">@Model.InsertDateTime</span>
                        <span class="priceTitr">کد خبر:</span>
                        <span class="priceValue price">@Model.NewsCode</span>
                    </div>
                    <hr style="margin:7px;" />
                    <div>
                        <p>
                            <img class="bigImage img-responsive" alt=@Model.NewsTitle title=@Model.NewsTitle src="~/uploadedimages/news/ThumbNail/@Model.Image" />
                            @Html.Raw(Model.Summary)
                        </p>
                    </div>
                    <div class="buy">
                        <p>@Html.Raw(Model.NewsContent)</p>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="rollProductsMainDiv block" id="peoplarPrds">
            <div class="right-blocks-title">
                <h2>آخرین اخبار</h2>
                <a class="showalllink" href="#" title="تمام اخبار">مشاهده همه</a>
                <div class="clearb"></div>

            </div>
            <div class="paneBody">
                @Html.Action("GetLastNewsCol", "News", new { top = 5 })
            </div>
        </div>
    </div>

</div>

RavadGarWebSite/Views/News/List.cshtml
@model IEnumerable<RavadGarWebSite.Models.News>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/shared/_homeLayout.cshtml";
}

<div class="container" id="newsAllList">
    <div class="blockRow">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    @foreach (var item in Model)
                    {
                        <li>
                            <a href="#" class="smallArticleImage">
                                <img src="~/uploadedimages/news/ThumbNail/@item.Image">
                            </a>
                            <a href="/news/@item.NewsCode" class="articleTitle">@item.NewsTitle</a>
                            <br>
                            <span class="date">@item.InsertDateTime.Day - @item.InsertDateTime.Month - @item.InsertDateTime.Year</span>
                            <div class="clearb"></div>
                        </li>

                    }
                </ul>
            </div>
        </div>
    </div>
</div>